server {
    listen 80;
    server_name HOSTNAME.local;
    return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  ssl_certificate /etc/nginx/conf.d/HOSTNAME+1.pem;
  ssl_certificate_key /etc/nginx/conf.d/HOSTNAME+1-key.pem;

  server_name HOSTNAME.local;
   location / {
      set $fixed_destination $http_destination;
      if ( $http_destination ~* ^https(.*)$ ) {
         set $fixed_destination http$1;
      }
      proxy_set_header   Destination $fixed_destination;
      proxy_set_header   Depth $http_depth;
      proxy_set_header   Upgrade $http_upgrade;
      proxy_set_header   Connection keep-alive;
      proxy_set_header   Host $host;
      proxy_pass         http://svn-server:80;
   }
   client_max_body_size 0;
}