version: '3'
services:
  svn:
    build: ./svn
    restart: always
    container_name: 'svn-server'
    working_dir: '/home/svn'
    volumes:
      - ${SVN_DOCKER_VOLUME_DIR:-/mnt/dockervolumes/svn}:/home/svn


  plume-proxy:
    image: nginx:alpine
    restart: always
    depends_on:
      - svn
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./proxy:/etc/nginx/conf.d